/**
 * COLORIDO 2K26 — AVENGERS EVENT UNIVERSE
 * 16 Event-Mapped Avengers Champions + Global Iron Man & Spider-Man.
 * Each Avenger champions one official COLORIDO 2K26 discipline.
 * Pure event information: Event, Category, Division, Description, Rules, Schedule, Register CTA.
 */

import { getCharacterPrimaryImage, getCharacterImage } from '../config/characterAssets'

export const IRON_MAN_GLOBAL = {
  id: "avenger_iron_man",
  slug: "tekraft-events",
  name: "Iron Man",
  heroTitle: "Tekraft Events Ambassador",
  title: "Tekraft Events Ambassador",
  category: "all",
  tagline: "Engineering, Innovation & Technical Craft",
  themeColor: "#e11d48",
  glowColor: "rgba(225, 29, 72, 0.6)",
  accentColor: "#fbbf24",
  quote: "Welcome to COLORIDO 2K26! Build the future with creativity and engineering.",
  eventAction: "repulsor_blast",
}

export const MASTER_GUIDE = IRON_MAN_GLOBAL

export const SPIDERMAN_GLOBAL = {
  id: "avenger_spiderman",
  name: "Spider-Man",
  heroTitle: "Table Tennis — Boys Ambassador",
  tagline: "Agility, Speed & Kinetic Reflexes",
  themeColor: "#ef4444",
  glowColor: "rgba(239, 68, 68, 0.6)",
  accentColor: "#3b82f6",
  quote: "Step up to the table with speed, passion, and precision!",
}

export const JARVIS_AI = {
  id: "ai_jarvis",
  name: "J.A.R.V.I.S.",
  heroTitle: "COLORIDO Tactical Festival Guide",
  themeColor: "#38bdf8",
  glowColor: "rgba(56, 189, 248, 0.5)",
  accentColor: "#0284c7",
  quote: "All systems online. Festival telemetry operating at optimal efficiency.",
}

export const CHARACTERS = [
  // ── 10 CULTURAL AVENGERS ──────────────────────────────────
  {
    id: "avenger_vision",
    slug: "fine-arts",
    name: "Vision",
    heroTitle: "Fine Arts Ambassador",
    title: "Fine Arts Ambassador",
    category: "cultural",
    subCategory: "Fine Arts",
    eventName: "Fine Arts",
    division: "Solo",
    themeColor: "#eab308",
    glowColor: "rgba(234, 179, 8, 0.55)",
    accentColor: "#06b6d4",
    quote: "Channel pure artistic focus and chromatic imagination into every stroke.",
    eventDescription: "Showcase your artistic talent through painting, sketching, and creative visual expression on canvas. Live on-spot competition evaluated by an esteemed panel of artists.",
    rules: [
      "Time limit: 2 hours strictly observed",
      "Official drawing sheets and mediums provided",
      "Topic revealed on the spot at commencement",
      "Individual solo participation only"
    ],
    schedule: "Day 1 • 10:00 AM • Main Arts Studio",
    eventAction: "mind_beam",
    avatarBg: "linear-gradient(135deg, #713f12 0%, #ca8a04 100%)",
  },
  {
    id: "avenger_star_lord",
    slug: "music-band-solo",
    name: "Star-Lord",
    heroTitle: "Music & Band — Solo Ambassador",
    title: "Music & Band — Solo Ambassador",
    category: "cultural",
    subCategory: "Music & Band",
    eventName: "Music & Band — Solo",
    division: "Solo",
    themeColor: "#ec4899",
    glowColor: "rgba(236, 72, 153, 0.55)",
    accentColor: "#3b82f6",
    quote: "Own the microphone and deliver an unforgettable musical performance!",
    eventDescription: "Solo musical showcase celebrating vocalists and solo instrumentalists across western, classical, and fusion genres on the main soundstage.",
    rules: [
      "Time limit: 5 minutes per performance",
      "Participants must bring their own instruments",
      "Up to one instrumental accompanist permitted",
      "Pre-recorded backing vocals strictly prohibited"
    ],
    schedule: "Day 1 • 02:00 PM • Main Soundstage",
    eventAction: "cassette_groove",
    avatarBg: "linear-gradient(135deg, #831843 0%, #ec4899 100%)",
  },
  {
    id: "avenger_rocket_groot",
    slug: "music-band-group",
    name: "Rocket",
    heroTitle: "Music & Band — Group Ambassador",
    title: "Music & Band — Group Ambassador",
    category: "cultural",
    subCategory: "Music & Band",
    eventName: "Music & Band — Group",
    division: "Group (3–8)",
    themeColor: "#84cc16",
    glowColor: "rgba(132, 204, 22, 0.6)",
    accentColor: "#f59e0b",
    quote: "Crank the amplifiers and electrify the crowd with your collective sound!",
    eventDescription: "Battle of the Bands competition bringing collegiate bands together for a thunderous contest of original composition, tight rhythm, and live energy.",
    rules: [
      "Team size: 3 to 8 band members",
      "Time limit: 10 minutes including setup",
      "Full acoustic drum kit and PA system provided",
      "Dedicated sound check slot allotted before show"
    ],
    schedule: "Day 1 • 06:00 PM • Open Air Arena",
    eventAction: "blaster_jam",
    avatarBg: "linear-gradient(135deg, #365314 0%, #65a30d 100%)",
  },
  {
    id: "avenger_black_widow",
    slug: "dance-solo",
    name: "Black Widow",
    heroTitle: "Dance — Solo Ambassador",
    title: "Dance — Solo Ambassador",
    category: "cultural",
    subCategory: "Dance",
    eventName: "Dance — Solo",
    division: "Solo",
    themeColor: "#f43f5e",
    glowColor: "rgba(244, 63, 94, 0.55)",
    accentColor: "#38bdf8",
    quote: "Precision, agility, and artistic expression unite to command the stage.",
    eventDescription: "Solo dance championship spotlighting technical footwork, rhythmic execution, and stage charisma across classical, semi-classical, contemporary, or hip-hop.",
    rules: [
      "Time limit: 4 minutes maximum",
      "Any dance form or creative fusion permitted",
      "Props allowed with prior stage committee clearance",
      "Audio track submitted on USB drive at registration desk"
    ],
    schedule: "Day 2 • 10:30 AM • Main Auditorium",
    eventAction: "widow_sting",
    avatarBg: "linear-gradient(135deg, #881337 0%, #e11d48 100%)",
  },
  {
    id: "avenger_scarlet_witch",
    slug: "dance-group",
    name: "Scarlet Witch",
    heroTitle: "Dance — Group Ambassador",
    title: "Dance — Group Ambassador",
    category: "cultural",
    subCategory: "Dance",
    eventName: "Dance — Group",
    division: "Group (4–15)",
    themeColor: "#ef4444",
    glowColor: "rgba(239, 68, 68, 0.6)",
    accentColor: "#f43f5e",
    quote: "Synchronize your movement, elevate your formations, and mesmerize the arena.",
    eventDescription: "Group dance tournament demanding intricate team choreography, dynamic spatial transitions, and high synchronization across diverse dance genres.",
    rules: [
      "Team size: 4 to 15 performers",
      "Time limit: 8 minutes performance duration",
      "Costumes and creative props permitted",
      "Judged on synchronization, choreography, and overall impact"
    ],
    schedule: "Day 2 • 02:30 PM • Main Auditorium",
    eventAction: "chaos_hex",
    avatarBg: "linear-gradient(135deg, #7f1d1d 0%, #dc2626 100%)",
  },
  {
    id: "avenger_doctor_strange",
    slug: "choreoday",
    name: "Doctor Strange",
    heroTitle: "Choreoday — Theme Based Ambassador",
    title: "Choreoday — Theme Based Ambassador",
    category: "cultural",
    subCategory: "Choreoday",
    eventName: "Choreoday — Theme Based",
    division: "Team (6–20)",
    themeColor: "#f59e0b",
    glowColor: "rgba(245, 158, 11, 0.6)",
    accentColor: "#ea580c",
    quote: "Weave movement, music, and thematic storytelling into a visual masterpiece.",
    eventDescription: "Flagship theme-based choreography showcase fusing drama, expressive contemporary dance, and cinematic narrative into a unified stage experience.",
    rules: [
      "Team size: 6 to 20 performers",
      "Time limit: 12 minutes total on stage",
      "Clear thematic narrative must be articulated",
      "Elaborate stagecraft, voiceovers, and props welcome"
    ],
    schedule: "Day 2 • 06:30 PM • Grand Amphitheater",
    eventAction: "mandala_spin",
    avatarBg: "linear-gradient(135deg, #78350f 0%, #d97706 100%)",
  },
  {
    id: "avenger_loki",
    slug: "dramatics",
    name: "Loki",
    heroTitle: "Dramatics Ambassador",
    title: "Dramatics Ambassador",
    category: "cultural",
    subCategory: "Dramatics",
    eventName: "Dramatics",
    division: "Team (5–15)",
    themeColor: "#10b981",
    glowColor: "rgba(16, 185, 129, 0.55)",
    accentColor: "#eab308",
    quote: "Command the theatrical spotlight with emotion, wit, and compelling storytelling.",
    eventDescription: "Inter-collegiate theatre and drama championship featuring original skits, one-act stage plays, and silent mime performances with high production values.",
    rules: [
      "Team size: 5 to 15 actors and technicians",
      "Time limit: 15 minutes including stage setup",
      "Standard light and sound console provided",
      "Vulgarity or unparliamentary content strictly prohibited"
    ],
    schedule: "Day 1 • 11:30 AM • Theatre Hall",
    eventAction: "illusion_mirror",
    avatarBg: "linear-gradient(135deg, #064e3b 0%, #059669 100%)",
  },
  {
    id: "avenger_black_panther",
    slug: "fashion-show",
    name: "Black Panther",
    heroTitle: "Fashion Show Ambassador",
    title: "Fashion Show Ambassador",
    category: "cultural",
    subCategory: "Fashion Show",
    eventName: "Fashion Show",
    division: "Team (6–12)",
    themeColor: "#a855f7",
    glowColor: "rgba(168, 85, 247, 0.55)",
    accentColor: "#06b6d4",
    quote: "Step onto the runway with sovereign poise, elegance, and visionary style.",
    eventDescription: "Prestigious collegiate fashion tournament assessing couture creativity, runway walk choreography, thematic design coherence, and bespoke styling.",
    rules: [
      "Team size: 6 to 12 models and stylists",
      "Time limit: 10 minutes runway presentation",
      "Theme-based presentation with background music",
      "Costumes and styling must adhere to collegiate decency standards"
    ],
    schedule: "Day 2 • 08:00 PM • Grand Runway Arena",
    eventAction: "vibranium_pulse",
    avatarBg: "linear-gradient(135deg, #3b0764 0%, #7e22ce 100%)",
  },
  {
    id: "avenger_iron_man",
    slug: "tekraft-events",
    name: "Iron Man",
    heroTitle: "Tekraft Events Ambassador",
    title: "Tekraft Events Ambassador",
    category: "cultural",
    subCategory: "Tekraft Events",
    eventName: "Tekraft Events",
    division: "Solo / Team",
    themeColor: "#e11d48",
    glowColor: "rgba(225, 29, 72, 0.6)",
    accentColor: "#fbbf24",
    quote: "Engineer the future by blending technology, ingenuity, and hands-on craftsmanship.",
    eventDescription: "Technical and creative craft events challenging participants to build innovative physical prototypes, robotics, and creative technical installations.",
    rules: [
      "Solo or duo team participation",
      "Material specifications announced per sub-challenge",
      "Evaluation on innovation, technical execution, and aesthetic design",
      "Live prototype demonstration before jury"
    ],
    schedule: "Day 1 • 01:00 PM • Tech Hub Center",
    eventAction: "repulsor_blast",
    avatarBg: "linear-gradient(135deg, #991b1b 0%, #e11d48 100%)",
  },
  {
    id: "avenger_captain_america",
    slug: "literary",
    name: "Captain America",
    heroTitle: "Literary Ambassador",
    title: "Literary Ambassador",
    category: "cultural",
    subCategory: "Literary",
    eventName: "Literary",
    division: "Solo",
    themeColor: "#3b82f6",
    glowColor: "rgba(59, 130, 246, 0.55)",
    accentColor: "#ef4444",
    quote: "Articulate your convictions with clarity, intellectual honor, and persuasive eloquence.",
    eventDescription: "Collegiate literary competition celebrating parliamentary debate, extempore oratory, poetry recitation, and creative essay writing.",
    rules: [
      "Individual solo participation across designated tracks",
      "Debate formats follow standard parliamentary rules",
      "Preparation time: 3 minutes for extempore; on-spot topics",
      "Evaluated on argument structure, vocabulary, and delivery"
    ],
    schedule: "Day 1 • 09:30 AM • Seminar Hall",
    eventAction: "shield_ricochet",
    avatarBg: "linear-gradient(135deg, #1e3a8a 0%, #2563eb 100%)",
  },

  // ── 6 SPORTS AVENGERS ─────────────────────────────────────
  {
    id: "avenger_hulk",
    slug: "basketball-boys",
    name: "Hulk",
    heroTitle: "Basketball — Boys Ambassador",
    title: "Basketball — Boys Ambassador",
    category: "sports",
    subCategory: "Basketball",
    division: "boys",
    eventName: "Basketball — Boys",
    themeColor: "#22c55e",
    glowColor: "rgba(34, 197, 94, 0.6)",
    accentColor: "#15803d",
    quote: "Bring power, defensive hustle, and teamwork to dominate the court!",
    eventDescription: "Full-court 5v5 inter-collegiate men's basketball tournament with fast-paced transition offense, tactical set plays, and knockout brackets.",
    rules: [
      "Squad size: 7 to 12 registered players",
      "Standard FIBA tournament rules apply",
      "Four quarters of 10 minutes running time",
      "Valid institutional college ID cards mandatory"
    ],
    schedule: "Day 1 & 2 • 08:00 AM • Main Basketball Court",
    eventAction: "gamma_smash",
    avatarBg: "linear-gradient(135deg, #14532d 0%, #16a34a 100%)",
  },
  {
    id: "avenger_thor",
    slug: "volleyball-boys",
    name: "Thor",
    heroTitle: "Volleyball — Boys Ambassador",
    title: "Volleyball — Boys Ambassador",
    category: "sports",
    subCategory: "Volleyball",
    division: "boys",
    eventName: "Volleyball — Boys",
    themeColor: "#38bdf8",
    glowColor: "rgba(56, 189, 248, 0.6)",
    accentColor: "#f59e0b",
    quote: "Elevate above the net and strike with thunderous teamwork!",
    eventDescription: "National-level inter-collegiate men's volleyball championship featuring explosive offensive spikes, solid dual blocks, and relentless defensive digs.",
    rules: [
      "Squad size: 6 to 10 registered players",
      "Best of 3 sets (25 points each; deciding set 15 points)",
      "Standard FIVB rotational rules enforced by certified referees",
      "Valid college ID card mandatory for all rostered players"
    ],
    schedule: "Day 1 & 2 • 09:00 AM • Outdoor Sports Arena",
    eventAction: "lightning_strike",
    avatarBg: "linear-gradient(135deg, #0c4a6e 0%, #0284c7 100%)",
  },
  {
    id: "avenger_spiderman",
    slug: "table-tennis-boys",
    name: "Spider-Man",
    heroTitle: "Table Tennis — Boys Ambassador",
    title: "Table Tennis — Boys Ambassador",
    category: "sports",
    subCategory: "Table Tennis",
    division: "boys",
    eventName: "Table Tennis — Boys",
    themeColor: "#ef4444",
    glowColor: "rgba(239, 68, 68, 0.6)",
    accentColor: "#3b82f6",
    quote: "Fast paddle reflexes, heavy topspin, and swift counter-attacks take the match!",
    eventDescription: "Men's singles table tennis championship challenging competitors in rapid-fire rallies, heavy spin loops, and lightning defensive blocks.",
    rules: [
      "Individual singles knockout tournament",
      "Best of 5 games to 11 points (2-point lead required)",
      "Official ITTF approved tables and 40+ mm tournament balls",
      "Participants must provide their own certified racquets"
    ],
    schedule: "Day 1 • 10:00 AM • Indoor Sports Complex",
    eventAction: "web_sling",
    avatarBg: "linear-gradient(135deg, #7f1d1d 0%, #ef4444 100%)",
  },
  {
    id: "avenger_captain_marvel",
    slug: "throwball-girls",
    name: "Captain Marvel",
    heroTitle: "Throwball — Girls Ambassador",
    title: "Throwball — Girls Ambassador",
    category: "sports",
    subCategory: "Throwball",
    division: "girls",
    eventName: "Throwball — Girls",
    themeColor: "#facc15",
    glowColor: "rgba(250, 204, 21, 0.6)",
    accentColor: "#3b82f6",
    quote: "Higher, further, faster! Launch fast throws and defend the court with passion!",
    eventDescription: "Inter-collegiate women's throwball tournament highlighting synchronized court defense, high-velocity over-the-net returns, and strategic tactical sets.",
    rules: [
      "Squad size: 7 to 12 registered female players",
      "Standard throwball court dimensions and net height",
      "Ball must be caught with both hands and released within 3 seconds",
      "Valid institutional college ID cards mandatory"
    ],
    schedule: "Day 1 & 2 • 08:30 AM • Central Grounds Court",
    eventAction: "photon_blast",
    avatarBg: "linear-gradient(135deg, #854d0e 0%, #eab308 100%)",
  },
  {
    id: "avenger_hawkeye",
    slug: "tennikoit-girls",
    name: "Hawkeye",
    heroTitle: "TenniKoit — Girls Ambassador",
    title: "TenniKoit — Girls Ambassador",
    category: "sports",
    subCategory: "TenniKoit",
    division: "girls",
    eventName: "TenniKoit — Girls",
    themeColor: "#8b5cf6",
    glowColor: "rgba(139, 92, 246, 0.6)",
    accentColor: "#06b6d4",
    quote: "Pinpoint accuracy, steady focus, and quick reflexes control the ring.",
    eventDescription: "Women's singles TenniKoit ring tournament testing swift single-handed catches, pinpoint trajectory delivery, and baseline court coverage.",
    rules: [
      "Individual singles knockout competition",
      "Single-handed catch and immediate single-handed return required",
      "Fault line and body touch regulations strictly observed",
      "Valid institutional college ID cards mandatory"
    ],
    schedule: "Day 1 • 11:00 AM • TenniKoit Court",
    eventAction: "arrow_release",
    avatarBg: "linear-gradient(135deg, #4c1d95 0%, #7c3aed 100%)",
  },
  {
    id: "avenger_ant_man",
    slug: "table-tennis-girls",
    name: "Ant-Man",
    heroTitle: "Table Tennis — Girls Ambassador",
    title: "Table Tennis — Girls Ambassador",
    category: "sports",
    subCategory: "Table Tennis",
    division: "girls",
    eventName: "Table Tennis — Girls",
    themeColor: "#ec4899",
    glowColor: "rgba(236, 72, 153, 0.6)",
    accentColor: "#fbbf24",
    quote: "Size up the angles, master your spins, and outmaneuver the competition!",
    eventDescription: "Women's singles table tennis championship emphasizing pinpoint ball placement, tactical slice defense, and high-velocity forehand drives.",
    rules: [
      "Individual singles knockout tournament",
      "Best of 5 games to 11 points (2-point lead required)",
      "Official ITTF approved tables and 40+ mm tournament balls",
      "Participants must provide their own certified racquets"
    ],
    schedule: "Day 1 • 02:00 PM • Indoor Sports Complex",
    eventAction: "quantum_sting",
    avatarBg: "linear-gradient(135deg, #831843 0%, #db2777 100%)",
  },
]

export function getCharacterBySlug(slug) {
  const c = CHARACTERS.find(c => c.slug === slug) || IRON_MAN_GLOBAL
  return { ...c, title: c.heroTitle || c.title || c.name }
}

export function getCharacterById(id) {
  if (id === IRON_MAN_GLOBAL.id) return { ...IRON_MAN_GLOBAL, title: IRON_MAN_GLOBAL.heroTitle }
  if (id === SPIDERMAN_GLOBAL.id) return { ...SPIDERMAN_GLOBAL, title: SPIDERMAN_GLOBAL.heroTitle }
  const c = CHARACTERS.find(c => c.id === id) || IRON_MAN_GLOBAL
  return { ...c, title: c.heroTitle || c.title || c.name }
}

export function getCharactersByCategory(category) {
  const list = (!category || category === "all") ? CHARACTERS : CHARACTERS.filter(c => c.category === category)
  return list.map(c => ({ ...c, title: c.heroTitle || c.title || c.name }))
}
